<?php
/**
 * WARNING! DO NOT EDIT THIS FILE DIRECTLY!
 *
 * FOR CUSTOM CSS USE THE PLUGIN THEME OPTIONS->CUSTOM CSS PANEL.
 */

/* Prevent direct access */
use WPDRMS\ASP\Utils\Css;defined('ABSPATH') or die("You can't access this file directly.");
?>
<?php if ($use_strong_compatibility == true): ?>
    <?php echo $asp_div_ids1; ?>,
    <?php echo $asp_set_ids1; ?>,
    <?php echo $asp_res_ids1; ?>,
    <?php echo $asp_div_ids2; ?>,
    <?php echo $asp_res_ids2; ?>,
    <?php echo $asp_set_ids2; ?>,
<?php endif; ?>
<?php echo $asp_res_ids; ?>,
<?php echo $asp_res_ids; ?> *,
<?php echo $asp_div_ids; ?>,
<?php echo $asp_div_ids; ?> *,
<?php echo $asp_set_ids; ?>,
<?php echo $asp_set_ids; ?> * {
    -webkit-box-sizing: content-box; /* Safari/Chrome, other WebKit */
    -moz-box-sizing: content-box; /* Firefox, other Gecko */
    -ms-box-sizing: content-box;
    -o-box-sizing: content-box;
    box-sizing: content-box;
    border: 0;
    border-radius: 0;
    text-transform: none;
    text-shadow: none;
    box-shadow: none;
    text-decoration: none;
    text-align: left;
    letter-spacing: normal;
}

<?php if ($use_strong_compatibility == true): ?>
    <?php echo $asp_div_ids1; ?>,
    <?php echo $asp_set_ids1; ?>,
    <?php echo $asp_res_ids1; ?>,
    <?php echo $asp_div_ids2; ?>,
    <?php echo $asp_res_ids2; ?>,
    <?php echo $asp_set_ids2; ?>,
<?php endif; ?>
<?php echo $asp_res_ids; ?>,
<?php echo $asp_div_ids; ?>,
<?php echo $asp_set_ids; ?> {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    -ms-box-sizing: border-box;
    -o-box-sizing: border-box;
    box-sizing: border-box;
}

/* Margin and padding gets wrecked if set with compatibility.. */
<?php echo $asp_res_ids; ?>,
<?php echo $asp_res_ids; ?> *,
<?php echo $asp_div_ids; ?>,
<?php echo $asp_div_ids; ?> *,
<?php echo $asp_set_ids; ?>,
<?php echo $asp_set_ids; ?> * {
    padding: 0;
    margin: 0;
}

.wpdreams_clear {
    clear: both;
}

.asp_w_container_<?php echo $id; ?> {
	width: <?php echo w_isset_def($style['box_width'], '100%'); ?>;
<?php if ($style['box_alignment'] == "center"): ?>
	margin-left: auto;
	margin-right: auto;
<?php elseif ($style['box_alignment'] == "left"): ?>
	margin-right: auto;
<?php elseif ($style['box_alignment'] == "right"): ?>
	margin-left: auto;
<?php endif; ?>
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_div_ids1; ?>,
    <?php echo $asp_div_ids2; ?>,
<?php endif; ?>
<?php echo $asp_div_ids; ?> {
  width: 100%;
  height: auto;
  max-height: none;
  border-radius: 5px;
  background: #d1eaff;
  margin-top: <?php echo esc_attr( $style['box_margin_top'] ); ?>;
  margin-bottom: <?php echo esc_attr( $style['box_margin_bottom'] ); ?>;
  <?php wpdreams_gradient_css($style['boxbackground']); ?>
  overflow: hidden;
  <?php echo $style['boxborder']; ?>
  <?php echo $style['boxshadow']; ?>
}

<?php if ( $style['box_width'] != $style['box_width_tablet'] ): ?>
@media only screen and (min-width: 641px) and (max-width: 1024px) {
	.asp_w_container_<?php echo $id; ?> {
		width: <?php echo w_isset_def($style['box_width_tablet'], '100%'); ?>;
	}
    div.asp_main_container.asp_w+[id*=asp-try-<?php echo $id; ?>] {
        width: <?php echo w_isset_def($style['box_width_tablet'], '100%'); ?>;
    }
}
<?php endif; ?>

<?php if ( $style['box_width'] != $style['box_width_phone'] ): ?>
@media only screen and (max-width: 640px) {
	.asp_w_container_<?php echo $id; ?> {
		width: <?php echo w_isset_def($style['box_width_phone'], '100%'); ?>;
	}
    div.asp_main_container.asp_w+[id*=asp-try-<?php echo $id; ?>] {
        width: <?php echo w_isset_def($style['box_width_phone'], '100%'); ?>;
    }
}
<?php endif; ?>

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_div_ids1; ?> .probox,
    <?php echo $asp_div_ids2; ?> .probox,
<?php endif; ?>
<?php echo $asp_div_ids; ?> .probox {
  margin: <?php echo $style['boxmargin']; ?>;
  height: <?php echo $style['boxheight']; ?>;
  <?php wpdreams_gradient_css($style['inputbackground']); ?>
  <?php echo $style['inputborder']; ?>
  <?php echo $style['inputshadow']; ?>
}

<?php
    $_box_pos = w_isset_def($style['box_compact_position'], 'static');
?>

<?php if (w_isset_def($style['box_compact_layout'], 0) == 1): ?>

    #asp_absolute_overlay {
        background: <?php echo w_isset_def($style['box_compact_overlay_color'], 'rgba(255, 255, 255, 0.5)'); ?>;
    }

    <?php if ($use_compatibility == true): ?>
        <?php echo $asp_div_ids1; ?>.asp_compact .probox,
        <?php echo $asp_div_ids2; ?>.asp_compact .probox,
    <?php endif; ?>
    <?php echo $asp_div_ids; ?>.asp_compact .probox {
        width: <?php echo wpdreams_width_from_px($style['boxheight']); ?>px;
    }

	<?php if ($_box_pos != 'static'): ?>
		<?php echo $asp_container_class; ?>.asp_compact {
			width: auto;
		}
		<?php if ($use_compatibility == true): ?>
			<?php echo $asp_div_ids1; ?>.asp_compact,
			<?php echo $asp_div_ids2; ?>.asp_compact,
		<?php endif; ?>
		<?php echo $asp_div_ids; ?>.asp_compact {
			width: auto;
			display: inline-block;
			float: <?php echo w_isset_def($style['box_compact_float'], 'inherit'); ?>;
			position: <?php echo $_box_pos; ?>;
			<?php if ($_box_pos) {
				$screen_pos = wpdreams_four_to_array(w_isset_def($style['box_compact_screen_position'], '||20%||auto||0px||auto||'));
				echo "
				top: ".$screen_pos['top'].";
				bottom: ".$screen_pos['bottom'].";
				right: ".$screen_pos['right'].";
				left: ".$screen_pos['left'].";";
			}?>
			z-index: <?php echo w_isset_def($style['box_compact_position_z'], '1000'); ?>;
		}
	<?php else: ?>
		<?php if ($use_compatibility == true): ?>
			<?php echo $asp_div_ids1; ?>.asp_compact,
			<?php echo $asp_div_ids2; ?>.asp_compact,
		<?php endif; ?>
		<?php echo $asp_div_ids; ?>.asp_compact {
			width: auto;
			float: <?php echo w_isset_def($style['box_compact_float'], 'inherit'); ?>;
		}
		<?php echo $asp_container_class; ?>.asp_compact {
			width: auto;
			display: inline-block;
			float: <?php echo w_isset_def($style['box_compact_float'], 'inherit'); ?>;
			position: <?php echo $_box_pos; ?>;
			<?php if ($_box_pos) {
				$screen_pos = wpdreams_four_to_array(w_isset_def($style['box_compact_screen_position'], '||20%||auto||0px||auto||'));
				echo "
				top: ".$screen_pos['top'].";
				bottom: ".$screen_pos['bottom'].";
				right: ".$screen_pos['right'].";
				left: ".$screen_pos['left'].";";
			}?>
			z-index: <?php echo w_isset_def($style['box_compact_position_z'], '1000'); ?>;
		}
	<?php endif; ?>

    <?php if ($_box_pos != 'static') {
        echo "p.asp_compact[id*=asp-try-".$id."] {
            display: none;
            position: ".$_box_pos.";
            top: ".$screen_pos['top'].";
            bottom: ".$screen_pos['bottom'].";
            right: ".$screen_pos['right'].";
            left: ".$screen_pos['left'].";
            z-index: ".w_isset_def($style['box_compact_position_z'], 1000).";
        }";
    }?>
<?php endif; ?>

p[id*=asp-try-<?php echo $id; ?>] {
    color: <?php echo w_isset_def($style['frontend_suggestions_text_color'], 'rgb(85, 85, 85)'); ?> !important;
    display: block;
}

div.asp_main_container+[id*=asp-try-<?php echo $id; ?>] {
    <?php if ($style['box_alignment'] == "center"): ?>
        margin-left: auto;
        margin-right: auto;
    <?php elseif ($style['box_alignment'] == "left"): ?>
        margin-right: auto;
    <?php elseif ($style['box_alignment'] == "right"): ?>
        margin-left: auto;
    <?php endif; ?>
    width: <?php echo w_isset_def($style['box_width'], '100%'); ?>;
}

p[id*=asp-try-<?php echo $id; ?>] a {
    color: <?php echo w_isset_def($style['frontend_suggestions_keywords_color'], 'rgb(255, 181, 86)'); ?> !important;
}

p[id*=asp-try-<?php echo $id; ?>] a:after {
    color: <?php echo w_isset_def($style['frontend_suggestions_text_color'], 'rgb(85, 85, 85)'); ?> !important;
    display: inline;
    content: ',';
}

p[id*=asp-try-<?php echo $id; ?>] a:last-child:after {
    display: none;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_div_ids1; ?> .probox .proinput,
    <?php echo $asp_div_ids2; ?> .probox .proinput,
<?php endif; ?>
<?php echo $asp_div_ids; ?> .probox .proinput {
  <?php echo Css::font($style['inputfont']); ?>
    line-height: normal;
  flex-grow: 1;
  order: 5;
  /* Ipad and stuff.. */
  -webkit-flex-grow: 1;
  -webkit-order: 5;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_div_ids1; ?> .probox .proinput input.orig,
    <?php echo $asp_div_ids2; ?> .probox .proinput input.orig,
<?php endif; ?>
<?php echo $asp_div_ids; ?> .probox .proinput input.orig {
    <?php echo Css::font($style['inputfont']); ?>
    line-height: normal;
    border: 0;
    box-shadow: none;
    height: <?php echo wpdreams_width_from_px($style['boxheight']); ?>px;
    position: relative;
    z-index: 2;
    padding: 0 !important;
    padding-top: 2px !important;
    margin: -1px 0 0 -4px !important;
    width: 100%;
    background: transparent !important;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_div_ids1; ?> .probox .proinput input.autocomplete,
    <?php echo $asp_div_ids2; ?> .probox .proinput input.autocomplete,
<?php endif; ?>
<?php echo $asp_div_ids; ?> .probox .proinput input.autocomplete {
    <?php echo Css::font($style['inputfont']); ?>
    line-height: normal;
    opacity: 0.25;
    height: <?php echo wpdreams_width_from_px($style['boxheight']); ?>px;
    display: block;
    position: relative;
    z-index: 1;
    padding: 0 !important;
    margin: -1px 0 0 -4px !important;
    margin-top: -<?php echo (wpdreams_width_from_px($style['boxheight'])); ?>px !important;
    width: 100%;
    background: transparent !important;
}

<?php
/**
 * RTL STUFF
 */
?>
<?php if ($use_compatibility == true): ?>
    .rtl <?php echo $asp_div_ids1; ?> .probox .proinput input.orig,
    .rtl <?php echo $asp_div_ids2; ?> .probox .proinput input.orig,
    .rtl <?php echo $asp_div_ids1; ?> .probox .proinput input.autocomplete,
    .rtl <?php echo $asp_div_ids2; ?> .probox .proinput input.autocomplete,
<?php endif; ?>
.rtl <?php echo $asp_div_ids; ?> .probox .proinput input.orig,
.rtl <?php echo $asp_div_ids; ?> .probox .proinput input.autocomplete {
    <?php echo Css::font($style['inputfont']); ?>
    line-height: normal;
    direction: rtl;
    text-align: right;
}

<?php if ($use_compatibility == true): ?>
    .rtl <?php echo $asp_div_ids1; ?> .probox .proinput,
    .rtl <?php echo $asp_div_ids2; ?> .probox .proinput,
<?php endif; ?>
.rtl <?php echo $asp_div_ids; ?> .probox .proinput {
    /*float: right;*/
    margin-right: 2px;
}

<?php if ($use_compatibility == true): ?>
    .rtl <?php echo $asp_div_ids1; ?> .probox .proloading,
    .rtl <?php echo $asp_div_ids1; ?> .probox .proclose,
    .rtl <?php echo $asp_div_ids2; ?> .probox .proloading,
    .rtl <?php echo $asp_div_ids2; ?> .probox .proclose,
<?php endif; ?>
.rtl <?php echo $asp_div_ids; ?> .probox .proloading,
.rtl <?php echo $asp_div_ids; ?> .probox .proclose {
    order: 3;
}


<?php echo $asp_div_ids; ?> .probox .proinput input.orig::-webkit-input-placeholder {
    <?php echo preg_replace( "/(line-height\:.*?)\;/", '', Css::font($style['inputfont']) ); ?>
    opacity: 0.85;
}
<?php echo $asp_div_ids; ?> .probox .proinput input.orig::-moz-placeholder {
    <?php echo preg_replace( "/(line-height\:.*?)\;/", '', Css::font($style['inputfont']) ); ?>
    opacity: 0.85;
}
<?php echo $asp_div_ids; ?> .probox .proinput input.orig:-ms-input-placeholder {
    <?php echo preg_replace( "/(line-height\:.*?)\;/", '', Css::font($style['inputfont']) ); ?>
    opacity: 0.85;
}
<?php echo $asp_div_ids; ?> .probox .proinput input.orig:-moz-placeholder {
    <?php echo preg_replace( "/(line-height\:.*?)\;/", '', Css::font($style['inputfont']) ); ?>
    opacity: 0.85;
    line-height: normal !important;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_div_ids1; ?> .probox .proinput input.autocomplete,
    <?php echo $asp_div_ids2; ?> .probox .proinput input.autocomplete,
<?php endif; ?>
<?php echo $asp_div_ids; ?> .probox .proinput input.autocomplete {
    <?php echo Css::font($style['inputfont']); ?>
    line-height: normal;
    border: 0;
    box-shadow: none;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_div_ids1; ?> .probox .proloading,
    <?php echo $asp_div_ids1; ?> .probox .proclose,
    <?php echo $asp_div_ids1; ?> .probox .promagnifier,
    <?php echo $asp_div_ids1; ?> .probox .prosettings,
    <?php echo $asp_div_ids2; ?> .probox .proloading,
    <?php echo $asp_div_ids2; ?> .probox .proclose,
    <?php echo $asp_div_ids2; ?> .probox .promagnifier,
    <?php echo $asp_div_ids2; ?> .probox .prosettings,
<?php endif; ?>
<?php echo $asp_div_ids; ?> .probox .proloading,
<?php echo $asp_div_ids; ?> .probox .proclose,
<?php echo $asp_div_ids; ?> .probox .promagnifier,
<?php echo $asp_div_ids; ?> .probox .prosettings {
  width: <?php echo wpdreams_width_from_px($style['boxheight']); ?>px;
  height: <?php echo wpdreams_width_from_px($style['boxheight']); ?>px;
  flex: 0 0 <?php echo wpdreams_width_from_px($style['boxheight']); ?>px;
  flex-grow: 0;
  order: 7;
    /* Ipad and stuff.. */
    -webkit-flex: 0 0 <?php echo wpdreams_width_from_px($style['boxheight']); ?>px;
    -webkit-flex-grow: 0;
    -webkit-order: 7;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_div_ids1; ?> .probox .proclose svg,
    <?php echo $asp_div_ids2; ?> .probox .proclose svg,
<?php endif; ?>
<?php echo $asp_div_ids; ?> .probox .proclose svg {
     fill: <?php echo $style['close_icon_fill']; ?>;
     background: <?php echo $style['close_icon_background']; ?>;
     box-shadow: 0px 0px 0px 2px <?php echo $style['close_icon_outline']; ?>;
}

<?php if ($use_compatibility == true): ?>
	<?php echo $asp_div_ids1; ?> .probox .proloading,
	<?php echo $asp_div_ids2; ?> .probox .proloading,
<?php endif; ?>
<?php echo $asp_div_ids; ?> .probox .proloading {
    width: <?php echo wpdreams_width_from_px($style['boxheight']); ?>px;
    height: <?php echo wpdreams_width_from_px($style['boxheight']); ?>px;
    min-width: <?php echo wpdreams_width_from_px($style['boxheight']); ?>px;
    min-height: <?php echo wpdreams_width_from_px($style['boxheight']); ?>px;
    max-width: <?php echo wpdreams_width_from_px($style['boxheight']); ?>px;
    max-height: <?php echo wpdreams_width_from_px($style['boxheight']); ?>px;
}

<?php if ($use_compatibility == true): ?>
	<?php echo $asp_div_ids1; ?> .probox .proloading .asp_loader,
	<?php echo $asp_div_ids2; ?> .probox .proloading .asp_loader,
<?php endif; ?>
<?php echo $asp_div_ids; ?> .probox .proloading .asp_loader {
    width: <?php echo wpdreams_width_from_px($style['boxheight']) - 4; ?>px;
    height: <?php echo wpdreams_width_from_px($style['boxheight']) - 4; ?>px;
    min-width: <?php echo wpdreams_width_from_px($style['boxheight']) - 4; ?>px;
    min-height: <?php echo wpdreams_width_from_px($style['boxheight']) - 4; ?>px;
    max-width: <?php echo wpdreams_width_from_px($style['boxheight']) - 4; ?>px;
    max-height: <?php echo wpdreams_width_from_px($style['boxheight']) - 4; ?>px;
}

<?php if ($use_compatibility == true): ?>
	<?php echo $asp_div_ids1; ?> .probox .promagnifier,
	<?php echo $asp_div_ids2; ?> .probox .promagnifier,
<?php endif; ?>
<?php echo $asp_div_ids; ?> .probox .promagnifier {
	width: auto;
	height: <?php echo wpdreams_width_from_px($style['boxheight']); ?>px;
	flex: 0 0 auto;
	order: 7;
	/* Ipad and stuff.. */
	-webkit-flex: 0 0 auto;
	-webkit-order: 7;
}

<?php if( w_isset_def($style['hide_magnifier'], 0) == 1 && w_isset_def($style['display_search_text'], 0) == 0 ): ?>
    <?php echo $asp_div_ids; ?> .probox .promagnifier {
        display: none;
    }
<?php endif; ?>

<?php echo $asp_div_ids; ?> .probox .promagnifier:focus-visible {
	outline: black outset;
}

<?php if ($use_compatibility == true): ?>
	<?php echo $asp_div_ids1; ?> .probox .promagnifier .innericon,
	<?php echo $asp_div_ids2; ?> .probox .promagnifier .innericon,
<?php endif; ?>
<?php echo $asp_div_ids; ?> .probox .promagnifier .innericon {
	display: block;
	width: <?php echo wpdreams_width_from_px($style['boxheight']); ?>px;
	height: <?php echo wpdreams_width_from_px($style['boxheight']); ?>px;
	float: right;
}

<?php if ($use_compatibility == true): ?>
	<?php echo $asp_div_ids1; ?> .probox .promagnifier .asp_text_button,
	<?php echo $asp_div_ids2; ?> .probox .promagnifier .asp_text_button,
<?php endif; ?>
<?php echo $asp_div_ids; ?> .probox .promagnifier .asp_text_button {
	display: block;
	width: auto;
	height: <?php echo wpdreams_width_from_px($style['boxheight']); ?>px;
	float: <?php echo w_isset_def($style["search_text_position"], 'right'); ?>;
	margin: 0;
<?php if( w_isset_def($style['hide_magnifier'], 0) == 1 ): ?>
	padding: 0 10px;
<?php else: ?>
	<?php if( w_isset_def($style['search_text_position'], 'right') == "right" ): ?>
	    padding: 0 10px 0 2px;
	<?php else: ?>
		padding: 0 2px 0 10px;
	<?php endif; ?>
<?php endif; ?>
    <?php echo Css::font($style['search_text_font']); ?>
    /* to center the text, this must be identical with the height */
    line-height: <?php echo wpdreams_width_from_px($style['boxheight']); ?>px;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_div_ids1; ?> .probox .promagnifier .innericon svg,
    <?php echo $asp_div_ids2; ?> .probox .promagnifier .innericon svg,
<?php endif; ?>
<?php echo $asp_div_ids; ?> .probox .promagnifier .innericon svg {
  fill: <?php echo $style['magnifierimage_color']; ?>;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_div_ids1; ?> .probox .prosettings .innericon svg,
    <?php echo $asp_div_ids2; ?> .probox .prosettings .innericon svg,
<?php endif; ?>
<?php echo $asp_div_ids; ?> .probox .prosettings .innericon svg {
  fill: <?php echo $style['settingsimage_color']; ?>;
}

<?php if (w_isset_def($style['loadingimage_custom'], "") != ""): ?>
    <?php echo $asp_div_ids; ?> .probox .proloading,
    <?php echo $asp_res_ids; ?> .asp_res_loader .asp_custom_loader {
        background-image: url("<?php echo  $style['loadingimage_custom']; ?>");
        background-size: contain;
        background-position: center;
        background-repeat: no-repeat;
    }
    <?php echo $asp_res_ids; ?> .asp_res_loader .asp_custom_loader {
        height: 200px;
    }
<?php endif; ?>


<?php if ($use_compatibility == true): ?>
    <?php echo $asp_div_ids1; ?> .probox .promagnifier,
    <?php echo $asp_div_ids2; ?> .probox .promagnifier,
<?php endif; ?>
<?php echo $asp_div_ids; ?> .probox .promagnifier {
  <?php if( w_isset_def($style['display_search_text'], 0) == 1 ): ?>
	  width: auto;
  <?php else: ?>
      width: <?php echo (wpdreams_width_from_px($style['boxheight'])-2*wpdreams_border_width($style['magnifierbackgroundborder'])); ?>px;
  <?php endif; ?>
  height: <?php echo (wpdreams_width_from_px($style['boxheight'])-2*wpdreams_border_width($style['magnifierbackgroundborder'])); ?>px;
  <?php wpdreams_gradient_css($style['magnifierbackground']); ?>
  background-position:center center;
  background-repeat: no-repeat;

  order: <?php echo w_isset_def($style['magnifier_position'], 'right') == 'right' ? 11 : 1; ?>;
  /* Ipad and stuff fix */
  -webkit-order: <?php echo w_isset_def($style['magnifier_position'], 'right') == 'right' ? 11 : 1; ?>;
  float: <?php echo $style['magnifier_position']; ?>; /* IE9, no flexbox */
  <?php echo $style['magnifierbackgroundborder']; ?>
  <?php echo $style['magnifierboxshadow']; ?>
  cursor: pointer;
  background-size: 100% 100%;

  background-position:center center;
  background-repeat: no-repeat;
  cursor: pointer;
}


<?php if (w_isset_def($style['magnifierimage_custom'], "") != ""): ?>
    <?php echo $asp_div_ids1; ?> .probox .promagnifier .innericon,
    <?php echo $asp_div_ids2; ?> .probox .promagnifier .innericon,
    <?php echo $asp_div_ids; ?> .probox .promagnifier .innericon {
    background-image: url("<?php echo  $style['magnifierimage_custom']; ?>");
    }
<?php elseif (pathinfo($style['magnifierimage'], PATHINFO_EXTENSION)!='svg'): ?>
    <?php echo $asp_div_ids1; ?> .probox .promagnifier .innericon,
    <?php echo $asp_div_ids2; ?> .probox .promagnifier .innericon,
    <?php echo $asp_div_ids; ?> .probox .promagnifier .innericon {
    background-image: url("<?php echo  plugins_url().$style['magnifierimage']; ?>");
    }
<?php endif; ?>

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_div_ids1; ?> .probox .prosettings,
    <?php echo $asp_div_ids2; ?> .probox .prosettings,
<?php endif; ?>
<?php echo $asp_div_ids; ?> .probox .prosettings {
  width: <?php echo (wpdreams_width_from_px($style['boxheight'])-2*wpdreams_border_width($style['settingsbackgroundborder'])); ?>px;
  height: <?php echo (wpdreams_width_from_px($style['boxheight'])-2*wpdreams_border_width($style['settingsbackgroundborder'])); ?>px;
  <?php wpdreams_gradient_css($style['settingsbackground']); ?>
  background-position:center center;
  background-repeat: no-repeat;
  order: <?php echo $style['settingsimagepos'] == 'right' ? 10 : 2; ?>;
  /* Ipad and stuff fix*/
  -webkit-order: <?php echo $style['settingsimagepos'] == 'right' ? 10 : 2; ?>;
  float: <?php echo $style['settingsimagepos']; ?>; /* IE9, no flexbox */
  <?php echo $style['settingsbackgroundborder']; ?>
  <?php echo $style['settingsboxshadow']; ?>
  cursor: pointer;
  background-size: 100% 100%;
  align-self: flex-end;
}

<?php if (w_isset_def($style['settingsimage_custom'], "") != ""): ?>
    <?php echo $asp_div_ids1; ?> .probox .prosettings .innericon,
    <?php echo $asp_div_ids2; ?> .probox .prosettings .innericon,
    <?php echo $asp_div_ids; ?> .probox .prosettings .innericon {
      background-image: url("<?php echo  $style['settingsimage_custom']; ?>");
    }
<?php elseif (pathinfo($style['settingsimage'], PATHINFO_EXTENSION)!='svg'): ?>
    <?php echo $asp_div_ids1; ?> .probox .prosettings .innericon,
    <?php echo $asp_div_ids2; ?> .probox .prosettings .innericon,
    <?php echo $asp_div_ids; ?> .probox .prosettings .innericon {
    background-image: url("<?php echo  plugins_url().$style['settingsimage']; ?>");
    }
<?php endif; ?>

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?>,
    <?php echo $asp_res_ids2; ?>,
<?php endif; ?>
<?php echo $asp_res_ids; ?> {
    position: <?php echo (($style['resultsposition']=='hover')?'absolute':'static'); ?>;
    z-index: <?php echo (($style['resultsposition']=='hover')? intval($style['res_z_index']):1); ?>;
    width: <?php echo $style['results_width']; ?>;
    margin: <?php echo $style['results_margin']; ?>;
}
<?php if ( $style['results_width'] != $style['results_width_tablet'] ): ?>
@media only screen and (min-width: 641px) and (max-width: 1024px) {
    <?php if ($use_compatibility == true): ?>
        <?php echo $asp_res_ids1; ?>,
        <?php echo $asp_res_ids2; ?>,
    <?php endif; ?>
    <?php echo $asp_res_ids; ?> {
        width: <?php echo $style['results_width_tablet']; ?>;
    }
}
<?php endif; ?>
<?php if ( $style['results_width'] != $style['results_width_phone'] ): ?>
@media only screen and (max-width: 640px) {
    <?php if ($use_compatibility == true): ?>
        <?php echo $asp_res_ids1; ?>,
        <?php echo $asp_res_ids2; ?>,
    <?php endif; ?>
    <?php echo $asp_res_ids; ?> {
        width: <?php echo $style['results_width_phone']; ?>;
    }
}
<?php endif; ?>

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .asp_nores,
    <?php echo $asp_res_ids2; ?> .asp_nores,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .asp_nores {
	<?php echo $style['kw_suggest_border']; ?>
	<?php echo $style['kw_suggest_box_shadow']; ?>
    padding: <?php echo $style['kw_suggest_padding']; ?>;
    margin: <?php echo $style['kw_suggest_margin']; ?>;
    <?php echo Css::font($style['kw_suggest_font']); ?>
    font-weight: normal;
	background: <?php echo $style['kw_suggest_bg']; ?>;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .asp_nores .asp_nores_kw_suggestions,
    <?php echo $asp_res_ids2; ?> .asp_nores .asp_nores_kw_suggestions,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .asp_nores .asp_nores_kw_suggestions {
	color: <?php echo $style['kw_suggest_didyoumean_font_color']; ?>;
    font-weight: normal;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .asp_nores .asp_keyword,
    <?php echo $asp_res_ids2; ?> .asp_nores .asp_keyword,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .asp_nores .asp_keyword {
    padding: 0 8px 0 0;
    cursor: pointer;
	color: <?php echo $style['kw_suggest_kw_font_color']; ?>;
    font-weight: bold;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .asp_results_top,
    <?php echo $asp_res_ids2; ?> .asp_results_top,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .asp_results_top {
    background: <?php echo $style['ritb_bg']; ?>;
    <?php echo $style['ritb_border']; ?>
    padding: <?php echo $style['ritb_padding']; ?>;
    margin: <?php echo $style['ritb_margin']; ?>;
    text-align: center;
    <?php echo Css::font($style['ritb_font']); ?>
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .results .item,
    <?php echo $asp_res_ids2; ?> .results .item,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .results .item {
    height: <?php echo $style['resultitemheight']; ?>;
    background: <?php echo $style['resultscontainerbackground']; ?>;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .results .item.hovered,
    <?php echo $asp_res_ids2; ?> .results .item.hovered,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .results .item.hovered {
  <?php wpdreams_gradient_css($style['vresulthbg']); ?>
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .results .item .asp_image,
    <?php echo $asp_res_ids2; ?> .results .item .asp_image,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .results .item .asp_image {
  background-size: <?php echo w_isset_def($style['image_display_mode'], "cover"); ?>;
  background-repeat: no-repeat;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .results .item .asp_item_overlay_img,
    <?php echo $asp_res_ids2; ?> .results .item .asp_item_overlay_img,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .results .item .asp_item_overlay_img {
   background-size: <?php echo w_isset_def($style['image_display_mode'], "cover"); ?>;
   background-repeat: no-repeat;
}

<?php
  $_vimagew = wpdreams_width_from_px($style['hreswidth']);
  $_vimageh = wpdreams_width_from_px($style['hor_img_height']);
?>

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .results .item .asp_content,
    <?php echo $asp_res_ids2; ?> .results .item .asp_content,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .results .item .asp_content {
    overflow: hidden;
    background: transparent;
    margin: 0;
    padding: 0 10px;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .results .item .asp_content h3,
    <?php echo $asp_res_ids2; ?> .results .item .asp_content h3,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .results .item .asp_content h3 {
  margin: 0;
  padding: 0;
  display: inline-block;
  line-height: inherit;
  <?php echo Css::font($style['titlefont']); ?>
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .results .item .asp_content h3 a,
    <?php echo $asp_res_ids2; ?> .results .item .asp_content h3 a,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .results .item .asp_content h3 a {
  margin: 0;
  padding: 0;
  line-height: inherit;
  display: block;
  <?php echo Css::font($style['titlefont']); ?>
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .results .item .asp_content h3 a:hover,
    <?php echo $asp_res_ids2; ?> .results .item .asp_content h3 a:hover,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .results .item .asp_content h3 a:hover {
  <?php echo Css::font($style['titlefont']); ?>
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .results .item div.etc,
    <?php echo $asp_res_ids2; ?> .results .item div.etc,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .results .item div.etc {
  padding: 0;
  font-size: 13px;
  line-height: 1.3em;
  margin-bottom: 6px;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .results .item .etc .asp_author,
    <?php echo $asp_res_ids2; ?> .results .item .etc .asp_author,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .results .item .etc .asp_author {
  padding: 0;
  <?php echo Css::font($style['authorfont']); ?>
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .results .item .etc .asp_date,
    <?php echo $asp_res_ids2; ?> .results .item .etc .asp_date,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .results .item .etc .asp_date {
  margin: 0 0 0 10px;
  padding: 0;
  <?php echo Css::font($style['datefont']); ?>
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .results .item div.asp_content,
    <?php echo $asp_res_ids2; ?> .results .item div.asp_content,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .results .item div.asp_content {
    margin: 0;
    padding: 0;
    <?php echo Css::font($style['descfont']); ?>
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> span.highlighted,
    <?php echo $asp_res_ids2; ?> span.highlighted,
<?php endif; ?>
<?php echo $asp_res_ids; ?> span.highlighted {
    font-weight: bold;
    color: <?php echo $style['highlightcolor'] ?>;
    background-color: <?php echo $style['highlightbgcolor'] ?>;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> p.showmore,
    <?php echo $asp_res_ids2; ?> p.showmore,
<?php endif; ?>
<?php echo $asp_res_ids; ?> p.showmore {
  text-align: center;
  <?php echo Css::font($style['showmorefont']); ?>
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> p.showmore a,
    <?php echo $asp_res_ids2; ?> p.showmore a,
<?php endif; ?>
<?php echo $asp_res_ids; ?> p.showmore a {
    <?php echo Css::font($style['showmorefont']); ?>
    padding: 10px 5px;
    margin: 0 auto;
    background: <?php echo $style['showmorefont_bg']; ?>;
    display: block;
    text-align: center;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .asp_res_loader,
    <?php echo $asp_res_ids2; ?> .asp_res_loader,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .asp_res_loader {
    background: <?php echo $style['resultscontainerbackground']; ?>;
    height: 200px;
    padding: 10px;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?>.isotopic .asp_res_loader,
    <?php echo $asp_res_ids2; ?>.isotopic .asp_res_loader,
<?php endif; ?>
<?php echo $asp_res_ids; ?>.isotopic .asp_res_loader {
    background: <?php echo $style['i_res_container_bg']; ?>;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .asp_res_loader .asp_loader,
    <?php echo $asp_res_ids2; ?> .asp_res_loader .asp_loader,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .asp_res_loader .asp_loader {
    height: 200px;
    width: 200px;
    margin: 0 auto;
}


/* Search settings */
<?php
if ( $style['fss_hover_columns'] == "auto" )
    $_hov_cwidth = 'none';
else
    $_hov_cwidth = ($style['fss_hover_columns'] * $style['fss_column_width'] + 8) . 'px';

if ( $style['fss_block_columns'] == "auto" )
    $_blc_cwidth = 'none';
else
    $_blc_cwidth = ($style['fss_block_columns'] * $style['fss_column_width'] + 8) . 'px';
?>
<?php if ($use_compatibility == true): ?>
    <?php echo $asp_set_ids; ?>.searchsettings,
    <?php echo $asp_set_ids; ?>.searchsettings,
<?php endif; ?>
<?php echo $asp_set_ids; ?>.searchsettings  {
  direction: ltr;
  padding: 0;
  <?php wpdreams_gradient_css($style['settingsdropbackground']); ?>
  <?php echo $style['settingsdropboxshadow']; ?>;
  max-width: <?php echo $_hov_cwidth; ?>;
  z-index: 2;
}

<?php if ($use_compatibility == true): ?>
<?php echo $asp_set_ids; ?>.searchsettings.asp_s,
<?php echo $asp_set_ids; ?>.searchsettings.asp_s,
<?php endif; ?>
<?php echo $asp_set_ids; ?>.searchsettings.asp_s  {
	z-index: <?php echo intval($style['sett_z_index']) ?>;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_bset_ids1; ?>.searchsettings,
    <?php echo $asp_bset_ids2; ?>.searchsettings,
<?php endif; ?>
<?php echo $asp_bset_ids; ?>.searchsettings {
  max-width: <?php echo $_blc_cwidth; ?>;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_set_ids; ?>.searchsettings form,
    <?php echo $asp_set_ids; ?>.searchsettings form,
<?php endif; ?>
<?php echo $asp_set_ids; ?>.searchsettings form {
  display: <?php echo ( $style['fss_column_layout'] == "flex") ? 'flex' : 'block'; ?>;
<?php if ( $style['fss_column_layout'] == "column" ): ?>
    -moz-column-width: <?php echo $style['fss_column_width']; ?>px;
    -moz-column-fill: balance;
    -moz-column-gap: 0px;
    -webkit-column-width: <?php echo $style['fss_column_width']; ?>px;
    -webkit-column-gap: 0;
    column-width: <?php echo $style['fss_column_width']; ?>px;
    column-gap: 0;
    column-fill: balance;
<?php endif; ?>
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_bset_ids; ?>.searchsettings form,
    <?php echo $asp_bset_ids; ?>.searchsettings form,
<?php endif; ?>
<?php echo $asp_bset_ids; ?>.searchsettings form {
  display: <?php echo ( $style['fss_column_layout'] == "flex") ? 'flex' : 'block'; ?>;
<?php if ( $style['fss_column_layout'] == "column" ): ?>
    -moz-column-width: <?php echo $style['fss_column_width']; ?>px;
    -moz-column-fill: balance;
    -moz-column-gap: 0px;
    -webkit-column-width: <?php echo $style['fss_column_width']; ?>px;
    -webkit-column-gap: 0;
    column-width: <?php echo $style['fss_column_width']; ?>px;
    column-gap: 0;
    column-fill: balance;
<?php endif; ?>
}

<?php if ( $style['fss_column_layout'] == "column" ): ?>
    <?php if ($use_compatibility == true): ?>
        <?php echo $asp_bset_ids; ?>.searchsettings form>fieldset,
        <?php echo $asp_bset_ids; ?>.searchsettings form>fieldset,
    <?php endif; ?>
    <?php echo $asp_bset_ids; ?>.searchsettings form>fieldset {
      display: inline-block;
      vertical-align: top;
      float: none;
    }
    <?php if ($use_compatibility == true): ?>
        <?php echo $asp_set_ids; ?>.searchsettings form>fieldset,
        <?php echo $asp_set_ids; ?>.searchsettings form>fieldset,
    <?php endif; ?>
    <?php echo $asp_set_ids; ?>.searchsettings form>fieldset {
      display: inline-block;
      vertical-align: top;
      float: none;
    }
<?php endif; ?>

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_set_ids1; ?>.searchsettings div.asp_option_label,
    <?php echo $asp_set_ids2; ?>.searchsettings div.asp_option_label,
    <?php echo $asp_set_ids1; ?>.searchsettings .asp_label,
    <?php echo $asp_set_ids2; ?>.searchsettings .asp_label,
<?php endif; ?>
<?php echo $asp_set_ids; ?>.searchsettings div.asp_option_label,
<?php echo $asp_set_ids; ?>.searchsettings .asp_label {
  <?php echo Css::font($style['settingsdropfont']); ?>
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_set_ids1; ?>.searchsettings .asp_option_inner .asp_option_checkbox,
    <?php echo $asp_set_ids2; ?>.searchsettings .asp_option_inner .asp_option_checkbox,
<?php endif; ?>
<?php echo $asp_bset_ids; ?>.searchsettings .asp_option_inner .asp_option_checkbox,
<?php echo $asp_set_ids; ?>.searchsettings .asp_option_inner .asp_option_checkbox {
  <?php wpdreams_gradient_css($style['settingsdroptickbggradient']); ?>
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_set_ids1; ?>.searchsettings .asp_option_inner .asp_option_checkbox:after,
    <?php echo $asp_set_ids2; ?>.searchsettings .asp_option_inner .asp_option_checkbox:after,
    <?php echo $asp_bset_ids1; ?>.searchsettings .asp_option_inner .asp_option_checkbox:after,
    <?php echo $asp_bset_ids2; ?>.searchsettings .asp_option_inner .asp_option_checkbox:after,
<?php endif; ?>
<?php echo $asp_bset_ids; ?>.searchsettings .asp_option_inner .asp_option_checkbox:after,
<?php echo $asp_set_ids; ?>.searchsettings .asp_option_inner .asp_option_checkbox:after {
    font-family: 'asppsicons2';
    border: none;
    content: "\e800";
    display: block;
    position: absolute;
    top: 0;
    left: 0;
    font-size: 11px;
    color: <?php echo $style['settingsdroptickcolor'] ?>;
    margin: 1px 0 0 0px !important;
    line-height: 17px;
    text-align: center;
    text-decoration: none;
    text-shadow: none;
}

<?php echo $asp_bset_ids; ?>.searchsettings .asp_sett_scroll,
<?php echo $asp_set_ids; ?>.searchsettings .asp_sett_scroll {
	scrollbar-width: thin;
	scrollbar-color: <?php echo wpd_gradient_get_color_only($style['settings_overflow_color']); ?> transparent;
}

<?php echo $asp_bset_ids; ?>.searchsettings .asp_sett_scroll::-webkit-scrollbar,
<?php echo $asp_set_ids; ?>.searchsettings .asp_sett_scroll::-webkit-scrollbar {
	width: 7px;
}

<?php echo $asp_bset_ids; ?>.searchsettings .asp_sett_scroll::-webkit-scrollbar-track,
<?php echo $asp_set_ids; ?>.searchsettings .asp_sett_scroll::-webkit-scrollbar-track {
	background: transparent;
}

<?php echo $asp_bset_ids; ?>.searchsettings .asp_sett_scroll::-webkit-scrollbar-thumb,
<?php echo $asp_set_ids; ?>.searchsettings .asp_sett_scroll::-webkit-scrollbar-thumb {
	<?php if ($style['settings_overflow_autohide']): ?>
	background: transparent;
	<?php else: ?>
	background: <?php echo wpd_gradient_get_color_only($style['settings_overflow_color']); ?>;
	<?php endif; ?>
	border-radius: 5px;
	border: none;
}

<?php if ($style['settings_overflow_autohide']): ?>
	<?php echo $asp_bset_ids; ?>.searchsettings:hover .asp_sett_scroll::-webkit-scrollbar-thumb,
	<?php echo $asp_set_ids; ?>.searchsettings:hover .asp_sett_scroll::-webkit-scrollbar-thumb {
		background: <?php echo wpd_gradient_get_color_only($style['settings_overflow_color']); ?>;
	}
	@media (hover: none), (max-width: 500px) {
		<?php echo $asp_bset_ids; ?>.searchsettings .asp_sett_scroll::-webkit-scrollbar-thumb,
		<?php echo $asp_set_ids; ?>.searchsettings .asp_sett_scroll::-webkit-scrollbar-thumb {
			background: <?php echo wpd_gradient_get_color_only($style['settings_overflow_color']); ?>;
		}
	}
<?php endif; ?>

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_set_ids1; ?>.searchsettings .asp_sett_scroll,
    <?php echo $asp_set_ids2; ?>.searchsettings .asp_sett_scroll,
<?php endif; ?>
<?php echo $asp_set_ids; ?>.searchsettings .asp_sett_scroll {
  max-height: <?php echo $style['settings_boxes_height']; ?>;
  overflow: auto;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_bset_ids1; ?>.searchsettings .asp_sett_scroll,
    <?php echo $asp_bset_ids2; ?>.searchsettings .asp_sett_scroll,
<?php endif; ?>
<?php echo $asp_bset_ids; ?>.searchsettings .asp_sett_scroll {
  max-height: <?php echo $style['settings_boxes_height']; ?>;
  overflow: auto;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_set_ids1; ?>.searchsettings fieldset,
    <?php echo $asp_set_ids2; ?>.searchsettings fieldset,
<?php endif; ?>
<?php echo $asp_set_ids; ?>.searchsettings fieldset {
  width: <?php echo $style['fss_column_width']; ?>px;
  min-width: <?php echo $style['fss_column_width']; ?>px;
  max-width: 10000px;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_bset_ids1; ?>.searchsettings fieldset,
    <?php echo $asp_bset_ids2; ?>.searchsettings fieldset,
<?php endif; ?>
<?php echo $asp_bset_ids; ?>.searchsettings fieldset {
  width: <?php echo $style['fss_column_width']; ?>px;
  min-width: <?php echo $style['fss_column_width']; ?>px;
  max-width: 10000px;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_set_ids1; ?>.searchsettings fieldset legend,
    <?php echo $asp_set_ids2; ?>.searchsettings fieldset legend,
<?php endif; ?>
<?php echo $asp_set_ids; ?>.searchsettings fieldset legend {
  padding: 0 0 0 10px;
  margin: 0;
  background: transparent;
  <?php echo Css::font($style['exsearchincategoriestextfont']); ?>
}

<?php if ($style['fe_search_button'] == 1 || $style['fe_reset_button'] == 1): ?>
    <?php if ($use_compatibility == true): ?>
        <?php echo $asp_set_ids1; ?>.searchsettings fieldset.asp_s_btn_container .asp_sr_btn_flex,
        <?php echo $asp_set_ids2; ?>.searchsettings fieldset.asp_s_btn_container .asp_sr_btn_flex,
        <?php echo $asp_bset_ids1; ?>.searchsettings fieldset.asp_s_btn_container .asp_sr_btn_flex,
        <?php echo $asp_bset_ids2; ?>.searchsettings fieldset.asp_s_btn_container .asp_sr_btn_flex,
    <?php endif; ?>
    <?php echo $asp_set_ids; ?>.searchsettings fieldset.asp_s_btn_container .asp_sr_btn_flex,
    <?php echo $asp_bset_ids; ?>.searchsettings fieldset.asp_s_btn_container .asp_sr_btn_flex {
        padding: 0 0 0 10px !important;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        flex-grow: 1;
        flex-shrink: 1;
        justify-content: center;
        align-items: stretch;
    }
    <?php if ($use_compatibility == true): ?>
        .rtl <?php echo $asp_set_ids1; ?>.searchsettings fieldset.asp_s_btn_container,
        .rtl <?php echo $asp_set_ids2; ?>.searchsettings fieldset.asp_s_btn_container,
        .rtl <?php echo $asp_bset_ids1; ?>.searchsettings fieldset.asp_s_btn_container,
        .rtl <?php echo $asp_bset_ids2; ?>.searchsettings fieldset.asp_s_btn_container,
    <?php endif; ?>
        .rtl <?php echo $asp_set_ids; ?>.searchsettings fieldset.asp_s_btn_container,
        .rtl <?php echo $asp_bset_ids; ?>.searchsettings fieldset.asp_s_btn_container {
       padding: 0 10px 0 0 !important;
    }
    <?php if ($use_compatibility == true): ?>
        <?php echo $asp_set_ids1; ?>.searchsettings fieldset.asp_s_btn_container .asp_r_btn_div,
        <?php echo $asp_set_ids2; ?>.searchsettings fieldset.asp_s_btn_container .asp_r_btn_div,
        <?php echo $asp_bset_ids1; ?>.searchsettings fieldset.asp_s_btn_container .asp_r_btn_div,
        <?php echo $asp_bset_ids2; ?>.searchsettings fieldset.asp_s_btn_container .asp_r_btn_div,
    <?php endif; ?>
    <?php echo $asp_set_ids; ?>.searchsettings fieldset.asp_s_btn_container .asp_r_btn_div,
    <?php echo $asp_bset_ids; ?>.searchsettings fieldset.asp_s_btn_container .asp_r_btn_div {
       text-align: <?php echo $style['fe_rb_align']; ?>;
       min-width: <?php echo 150 - (50 * ($style['fe_search_button'] + $style['fe_reset_button'])); ?>%;
    }
    <?php if ($use_compatibility == true): ?>
        <?php echo $asp_set_ids1; ?>.searchsettings fieldset.asp_s_btn_container .asp_s_btn_div,
        <?php echo $asp_set_ids2; ?>.searchsettings fieldset.asp_s_btn_container .asp_s_btn_div,
        <?php echo $asp_bset_ids1; ?>.searchsettings fieldset.asp_s_btn_container .asp_s_btn_div,
        <?php echo $asp_bset_ids2; ?>.searchsettings fieldset.asp_s_btn_container .asp_s_btn_div,
    <?php endif; ?>
    <?php echo $asp_set_ids; ?>.searchsettings fieldset.asp_s_btn_container .asp_s_btn_div,
    <?php echo $asp_bset_ids; ?>.searchsettings fieldset.asp_s_btn_container .asp_s_btn_div {
       text-align: <?php echo $style['fe_sb_align']; ?>;
       min-width: <?php echo 150 - (50 * ($style['fe_search_button'] + $style['fe_reset_button'])); ?>%;
    }
<?php endif; ?>

<?php if ($style['fe_search_button'] == 1): ?>
    <?php if ($use_compatibility == true): ?>
        <?php echo $asp_set_ids1; ?>.searchsettings fieldset.asp_s_btn_container button.asp_search_btn.asp_s_btn,
        <?php echo $asp_set_ids2; ?>.searchsettings fieldset.asp_s_btn_container button.asp_search_btn.asp_s_btn,
        <?php echo $asp_bset_ids1; ?>.searchsettings fieldset.asp_s_btn_container button.asp_search_btn.asp_s_btn,
        <?php echo $asp_bset_ids2; ?>.searchsettings fieldset.asp_s_btn_container button.asp_search_btn.asp_s_btn,
    <?php endif; ?>
    <?php echo $asp_set_ids; ?>.searchsettings fieldset.asp_s_btn_container button.asp_search_btn.asp_s_btn,
    <?php echo $asp_bset_ids; ?>.searchsettings fieldset.asp_s_btn_container button.asp_search_btn.asp_s_btn {
      display: inline-block;
      cursor: pointer;
      vertical-align: middle;
      outline: none;
      width: auto;
      box-sizing: border-box;
      background: <?php echo $style['fe_sb_bg']; ?>;
      padding: <?php echo $style['fe_sb_padding']; ?>;
      margin: <?php echo $style['fe_sb_margin']; ?>;
      <?php echo $style['fe_sb_border']; ?>
      <?php echo $style['fe_sb_boxshadow']; ?>
      <?php echo Css::font($style['fe_sb_font']); ?>
    }
    <?php if ($use_compatibility == true): ?>
        <?php echo $asp_set_ids1; ?>.searchsettings fieldset.asp_s_btn_container button.asp_search_btn.asp_s_btn:active,
        <?php echo $asp_set_ids2; ?>.searchsettings fieldset.asp_s_btn_container button.asp_search_btn.asp_s_btn:active,
        <?php echo $asp_bset_ids1; ?>.searchsettings fieldset.asp_s_btn_container button.asp_search_btn.asp_s_btn:active,
        <?php echo $asp_bset_ids2; ?>.searchsettings fieldset.asp_s_btn_container button.asp_search_btn.asp_s_btn:active,
    <?php endif; ?>
    <?php echo $asp_set_ids; ?>.searchsettings fieldset.asp_s_btn_container button.asp_search_btn.asp_s_btn:active,
    <?php echo $asp_bset_ids; ?>.searchsettings fieldset.asp_s_btn_container button.asp_search_btn.asp_s_btn:active {
       transform: translateY(1px);
    }
<?php endif; ?>


<?php if ($style['fe_reset_button'] == 1): ?>
    <?php if ($use_compatibility == true): ?>
        <?php echo $asp_set_ids1; ?>.searchsettings fieldset.asp_s_btn_container button.asp_reset_btn.asp_r_btn,
        <?php echo $asp_set_ids2; ?>.searchsettings fieldset.asp_s_btn_container button.asp_reset_btn.asp_r_btn,
        <?php echo $asp_bset_ids1; ?>.searchsettings fieldset.asp_s_btn_container button.asp_reset_btn.asp_r_btn,
        <?php echo $asp_bset_ids2; ?>.searchsettings fieldset.asp_s_btn_container button.asp_reset_btn.asp_r_btn,
    <?php endif; ?>
    <?php echo $asp_set_ids; ?>.searchsettings fieldset.asp_s_btn_container button.asp_reset_btn.asp_r_btn,
    <?php echo $asp_bset_ids; ?>.searchsettings fieldset.asp_s_btn_container button.asp_reset_btn.asp_r_btn {
      display: inline-block;
      cursor: pointer;
      vertical-align: middle;
      outline: none;
      width: auto;
      box-sizing: border-box;
      background: <?php echo $style['fe_rb_bg']; ?>;
      padding: <?php echo $style['fe_rb_padding']; ?>;
      margin: <?php echo $style['fe_rb_margin']; ?>;
      <?php echo $style['fe_rb_border']; ?>
      <?php echo $style['fe_rb_boxshadow']; ?>
      <?php echo Css::font($style['fe_rb_font']); ?>
    }
    <?php if ($use_compatibility == true): ?>
        <?php echo $asp_set_ids1; ?>.searchsettings fieldset.asp_s_btn_container button.asp_reset_btn.asp_r_btn:active,
        <?php echo $asp_set_ids2; ?>.searchsettings fieldset.asp_s_btn_container button.asp_reset_btn.asp_r_btn:active,
        <?php echo $asp_bset_ids1; ?>.searchsettings fieldset.asp_s_btn_container button.asp_reset_btn.asp_r_btn:active,
        <?php echo $asp_bset_ids2; ?>.searchsettings fieldset.asp_s_btn_container button.asp_reset_btn.asp_r_btn:active,
    <?php endif; ?>
    <?php echo $asp_set_ids; ?>.searchsettings fieldset.asp_s_btn_container button.asp_reset_btn.asp_r_btn:active,
    <?php echo $asp_bset_ids; ?>.searchsettings fieldset.asp_s_btn_container button.asp_reset_btn.asp_r_btn:active {
       transform: translateY(1px);
    }
<?php endif; ?>